// Machine-readable API error codes the UI maps to copy (`apiErrors.<code>`
// in the message catalogs). A LEAF module (no React, no next-intl) so the
// unit test can walk it against both catalogs in a plain node environment.

export const KNOWN_API_ERROR_CODES = [
  'network_error',
  'http_401',
  'rate_limited',
  'conflict',
  'illegal_event',
  'wallet_unavailable',
  'wallet_required',
  'self_payment_impossible',
  'hub_not_found',
  'hubs_too_close',
  'sender_owns_hub',
  'bond_above_cap',
  'parcel_too_big',
  'parcel_too_heavy',
  'undeclared_not_accepted',
  'hub_storage_too_short',
  'trip_not_found',
  'trip_not_active',
  'trip_expires_before_departure',
  'carrier_role_required',
  'not_at_hub',
  'not_the_sender',
  'fake_wallets_disabled',
  'nwc_invalid_connection_string',
  'nwc_connection_failed',
  'nwc_missing_required_methods',
  'wallet_missing_hold_support',
  'preview_pair_required',
  'pool_exhausted',
  'progress_below_minimum',
  // Part 2 — hub operations, handoffs, claim, reviews.
  'not_found',
  'not_a_hub',
  'hub_already_exists',
  'not_origin_hub',
  'not_custodian_hub',
  'qr_mismatch',
  'no_booked_leg',
  'not_a_checkout_party',
  'checkout_photo_required',
  'no_leg_in_transit',
  'not_arrival_hub',
  'not_departure_hub',
  'otp_invalid',
  'claim_token_invalid',
  'not_the_receiving_party',
  'parcel_not_idle_at_hub',
  'guard_failed',
  'hold_not_held',
  'instant_payment_failed',
  'shipment_not_closed',
  'review_window_closed',
  'not_a_participant',
  'self_review',
  'subject_role_not_effective',
  'already_reviewed',
] as const;
